name: Add your device
description: It will trigger a GitHub Actions that build for your devices
title: '[New Devices]'
body:
  - type: textarea
    id: description
    attributes:
      label: "test"
    validations:
      required: true
