name: Add your device
description: It will trigger a GitHub Actions that builds for your devices
title: '[New Devices]'
label: "Device Name"
body:
  - type: input
    id: device_codename
    attributes:
      label: "Device Codename"
      description: "Enter your device's codename (e.g., 'earth'). This is a required field."
      placeholder: "Enter device codename"
    validations:
      required: true

  - type: input
    id: kernel_sources
    attributes:
      label: "Device kernel sources"
      description: "Enter the URL to the kernel sources for your device (e.g., 'https://github.com/user/repo')."
      placeholder: "https://github.com/..."
    validations:
      required: true

  - type: input
    id: telegram_username
    attributes:
      label: "Telegram Username"
      description: "Generated flashable will send to your Telegram by a bot"
      placeholder: "Eg. ID: 7688567205"
    validations:
      required: true
