name: Device request
description: "Use this template to build for a new devices"
labels: 
  - action-trigger
assignees: []

body:
  - type: markdown
    attributes:
      value: test
  - type: input
    id: inputParameter
    attributes:
      label: "Device's kernel source"
      description: "Paste the link here!"
      placeholder: "test"
      required: true
  - type: dropdown
    id: actionType
    attributes:
      label: "Action Type"
      description: "Select the type of action to trigger."
      options:
        - "build"
        - "test"
        - "deploy"
      required: true
